config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :groups
  resources :strengths
  resources :teams

  resources :groups do
    member do
      get :generate_teams
      patch :run_sort
    end
  end

  root 'groups#index'

  # for lets encrypt ssl cert
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :teams

  validates :title, presence: true
  attr_accessor :team_size

  # processes stripe payment
  def process_payment
    customer = Stripe::Customer.create card: card_token

    Stripe::Charge.create customer: customer.id,
                          amount: 5000,
                          description: 'group purchase',
                          currency: 'usd'

  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @user = current_user
    @groups = @user.groups
    @teams = @user.teams
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  CHARS = ('0'..'9').to_a + ('A'..'Z').to_a + ('a'..'z').to_a
  def random_password(length=10)
    CHARS.sort_by { rand }.join[0...length]
  end

  def create
    create_params = group_params
    # generate random string for group code
    create_params[:code] = random_password(8);

    #SecureRandom.base64(5) is old generator
    @group = Group.new(create_params)
    @group.users << current_user

    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])

    teams = @group.teams
    teams.each do |team|
      team.users.each do |user|
        user.teams.delete(team)
        user.save
      end
    end
    teams.destroy_all
    @group.destroy

    redirect_to groups_path
  end

  def generate_teams
    @group = Group.find(params[:id])
  end

  def run_sort
    @group = Group.find(params[:id])
    users = @group.users.where(admin: false)

    # remove the user from their team for this group in case we're doing a re-sort
    users.each do |user|
      team = user.teams.where(group_id: @group.id)
      user.teams.delete(team)
      user.save
    end

    team_size = group_params[:team_size].to_i
    user_count = users.count

    # if we're doing a re-sort we'll need to get rid of teams that were previously formed
    @group.teams.destroy_all

    # create teams
    team_num = user_count/team_size
    team_num.times do
      team = Team.new(score: 0)
      team.save
      @group.teams << team
    end


    ## STRATEGIC ##
    strategic = find_strength(users, 'strategic thinking')
    users = users - strategic

    teams = @group.teams.order(:score)
    teams.each do |team|
      if strategic.any?
        index = find_user_for_team(team.users, strategic)
        team.users << strategic[index]
        team.score += 1
        team.save
        strategic.delete_at(index)
      end
    end

    # put any we didn't assign to a team back into users
    strategic.each do |s|
      users << s
    end

    ## EXECUTORS ##
    executors = find_strength(users, 'executing')
    users = users - executors

    teams = @group.teams.order(:score)
    teams.each do |team|
      if executors.any?
        index = find_user_for_team(team.users, executors)
        team.users << executors[index]
        team.score += 1
        team.save
        executors.delete_at(index)
      end
    end

    # put any we didn't assign to a team back into users
    executors.each do |e|
      users << e
    end

    ## INFLUENCERS ##
    influencers = find_strength(users, 'influencing')
    users = users - influencers

    teams = @group.teams.order(:score)
    teams.each do |team|
      if influencers.any?
        index = find_user_for_team(team.users, influencers)
        team.users << influencers[index]
        team.score += 1
        team.save
        influencers.delete_at(index)
      end
    end

    # put any we didn't assign to a team back into users
    influencers.each do |i|
      users << i
    end

    ## RELATIONSHIP BUILDERS ##
    relationship_builders = find_strength(users, 'relationship building')
    users = users - relationship_builders

    teams = @group.teams.order(:score)
    teams.each do |team|
      if relationship_builders.any?
        index = find_user_for_team(team.users, relationship_builders)
        team.users << relationship_builders[index]
        team.score += 1
        team.save
        relationship_builders.delete_at(index)
      end
    end

    # put any we didn't assign to a team back into users
    relationship_builders.each do |rb|
      users << rb
    end

    teams = @group.teams.order(:score)

    # add people to teams so team size is met
    teams.each do |team|
      while team.users.count < team_size
        index = find_user_for_team(team.users, users)
        team.users << users[index]
        team.save
        users.delete_at(index)
      end
    end

    # add extra people to teams with the lowest scores
    index = 0
    while users.any?
      team = teams[index]
      user_index = find_user_for_team(team.users, users)
      team.users << users[user_index]
      team.save
      users.delete_at(user_index)
      index += 1
      if index >= team_num
        index = 0
      end
    end

    redirect_to teams_path(group: @group)
  end

  private

    def group_params
      params.require(:group).permit(:title, :team_size, :hide_results)
    end

    def find_strength(users, strength)
      found = []
      count = 0
      users.each do |user|
        strengths = user.strengths
        strengths.each do |s|
          if s.domain == strength
            count += 1
          end
        end
        if count >= 2
          found << user
        end
        count = 0
      end
      found
    end

    def find_user_for_team(team_users, users)
      team_strengths = []
      team_users.each do |user|
        user.strengths.each do |s|
          team_strengths << s.name
        end
      end

      # keep track of the max diff count and the index of the user with them
      diff_count = 0
      user_index = 0
      result = user_index
      users.each do |user|
        diffs = 0
        user.strengths.each do |s|
          if not team_strengths.include?(s.name)
            diffs += 1
          end
        end

        if diffs > diff_count
          diff_count = diffs
          result = user_index
        end
        user_index += 0
      end
      result
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
	<style>
		.modal-content{
			background-color: #f2f5f8;
		}
		.modal-header{
			background-color: #ffffff;
		}
		.modal-rooter{
			background-color: #f2f5f8;
		}
	</style>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><font color = "23527C"><strong>New Group</strong></font></h4>
  </div>
  <div class="modal-body">
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label 'Hide team sort results from users' %><br>
      <%= f.check_box :hide_results %>
    </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= form_for @group do |f| %>
  <style>
    .modal-content{
      background-color: #f2f5f8;
    }
    .modal-header{
      background-color: #ffffff;
    }
    .modal-rooter{
      background-color: #f2f5f8;
    }
  </style>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><font color = "23527C"><strong>Edit Group</strong></font></h4>
  </div>
  <div class="modal-body">
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label 'hide results from users' %><br>
      <%= f.check_box :hide_results %>
    </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit 'Save Changes', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/generate_teams.html.erb
<%= form_for @group, :url => run_sort_group_path do |f| %>
  <style>
    .modal-content{
      background-color: #f2f5f8;
    }
    .modal-header{
      background-color: #ffffff;
    }
    .modal-rooter{
      background-color: #f2f5f8;
    }
  </style>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel"><font color = "23527C"><strong>Sort Teams</strong></font></h4>
    </div>
    <div class="modal-body">
      <p>
        <%= f.label :team_size %><br>
        <%= f.number_field :team_size %>
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= f.submit 'Run Sort', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/groups/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Reveal Bootstrap Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Reveal
    Theme URL: https://bootstrapmade.com/reveal-bootstrap-corporate-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="body">

<!--==========================
  Top Bar
============================-->
<!--<section id="topbar" class="d-none d-lg-block">-->
  <!--<div class="container clearfix">-->
    <!--<div class="contact-info float-left">-->
      <!--<i class="fa fa-envelope-o"></i> <a href="mailto:contact@example.com">contact@example.com</a>-->
      <!--<i class="fa fa-phone"></i> +1 5589 55488 55-->
    <!--</div>-->
  <!--</div>-->
<!--</section>-->

<!--==========================
  Header
============================-->
<header id="header">
  <div class="container">

    <div id="logo" class="pull-left">
      <h1>
        <%= link_to root_path do %>
          Team<span>Sort</span>
        <% end %>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="#body"><img src="img/logo.png" alt="" title="" /></a>-->
    </div>

    <nav id="nav-menu-container">
      <ul class="nav-menu">
        <!-- /.dropdown -->
        <li class="menu-has-children"><a href=""><i class="fa fa-user fa-fw"></i></a>
          <ul>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-gear fa-fw"></i> Edit Account
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out fa-fw"></i> Logout
              <% end %>
            </li>
          </ul>
        </li>
        <!-- /.dropdown -->
      </ul>
    </nav><!-- #nav-menu-container -->
  </div>
</header><!-- #header -->

<main id="main">

  <!--<section id="contact" class="wow fadeInUp">-->
  <section id="contact">
    <div class="container">
      <div class="section-header">
        <h2>Dashboard</h2>
        <% if current_user.admin %>
        <p>Manage your classes here. Distribute the unique sign up code to your students and run the sorting algorithm after they
        have all registered. You may re-sort as many times as you like.</p>
        <% else %>
        <p></p>
        <% end %>
      </div>
    </div>

    <div class="container">
      <% if current_user.admin %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                Manage Groups
              </div>
              <!-- /.panel-heading -->
              <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                    <tr>
                      <th>Title</th>
                      <th>Sign Up Code</th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @groups.each do |group| %>
                      <tr>
                        <td data-link="<%= group_path(group) %>"><%= group.title %></td>
                        <td data-link="<%= group_path(group) %>"><%= group.code %></td>
                        <td><%= link_to edit_group_path(group), 'data-toggle'=> 'modal', 'data-target'=> '#myModal2' do %>
                            <i class="fa fa-pencil" data-toggle="tooltip" title="Edit"></i>
                          <% end %>
                        </td>
                        <td><%= link_to group_path(group),
                                        method: :delete,
                                        data: { confirm: 'Are you sure you want to delete this Group?' } do %>
                            <i class="fa fa-trash-o" data-toggle="tooltip" title="Delete"></i>
                          <% end %>
                        </td>
                        <% if group.teams.any? %>
                          <td>
                            <%= link_to teams_path(group: group) do %>
                              <i class="fa fa-users" data-toggle="tooltip" title="Teams"></i>
                            <% end %>
                          </td>
                        <% else %>
                          <td>
                            <%= link_to generate_teams_group_path(group), 'data-toggle'=> 'modal', 'data-target'=> '#myModal3' do %>
                              <i class="fa fa-sort" data-toggle="tooltip" title="Sort Teams"></i>
                            <% end %>
                          </td>
                          <td>
                            <%= link_to generate_teams_group_path(group), 'data-toggle'=> 'modal', 'data-target'=> '#myModal3' do %>
                              <i class="fa fa-user-plus" data-toggle="tooltip" title="Edit Teams"></i>
                            <% end %>
                          </td>
                          <td></td>
                        <% end %>
                      </tr>
                    <% end %>
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
              </div>
              <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
          </div>
          <!-- /.col-lg-6 -->
        </div>
      <% else %>
        <% if @teams.none? %>
          <p>Thanks for signing up! Your instructor will provide you with further details.</p>
        <% else %>
          <% @teams.each do |team| %>
            <% if team.group.hide_results? %>
              <p>Thanks for signing up! Your instructor will provide you with further details.</p>
            <% else %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Team Contact Information</a>
                    <a id="myButtonControlID" href="#"><i class="fa fa-download pull-right"></i></a>
                  </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in">
                  <div class="panel-body" id="divTableDataHolder">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example2">
                      <thead>
                      <tr>
                        <th>Name</th>
                        <th>Email Address</th>
                      </tr>
                      </thead>
                      <tbody>
                      <% team.users.each do |user| %>
                        <tr class="odd gradeX">
                          <td> <%= user.first_name %> <%= user.last_name %> </td>
                          <td> <%= user.email %> </td>
                        </tr>
                      <% end %>
                      <tr>
                        <td></td>
                        <td></td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Strengths Grid</a>
                    <a id="myButtonControlID2" href="#"><i class="fa fa-download pull-right"></i></a>
                  </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse in">
                  <div class="panel-body">
                    <div class="dataTable_wrapper table-responsive" id="strength_grid">
                      <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                          <th></th>
                          <th></th>
                          <th colspan=9 bgcolor="#5C1F5C" style="color:white">EXECUTING</th>
                          <th colspan=8 bgcolor="#cd853f" style="color:white">INFLUENCING</th>
                          <th colspan=9 bgcolor="#24476B" style="color:white">RELATIONSHIP BUILDING</th>
                          <th colspan=8 bgcolor="#7A1919" style="color:white">STRATEGIC THINKING</th>
                        </tr>
                        <tr>
                          <th>Name</th>
                          <% Strength.order(:domain).each do |strength| %>
                            <th> <%= strength.name %> </th>
                          <% end %>
                        </tr>
                        </thead>
                        <tbody>
                        <% team.users.each do |user| %>
                          <tr class="odd gradeX">
                            <td> <%= user.first_name %> <%= user.last_name %> </td>
                            <% Strength.order(:domain).each do |s| %>
                              <% if s == user.strengths[0] %>
                                <td bgcolor="#7A1919" style="color:white">1</td>
                              <% elsif s == user.strengths[1] %>
                                <td bgcolor="#7A1919" style="color:white">2</td>
                              <% elsif s == user.strengths[2] %>
                                <td bgcolor="#7A1919" style="color:white">3</td>
                              <% elsif s == user.strengths[3] %>
                                <td bgcolor="#7A1919" style="color:white">4</td>
                              <% elsif s == user.strengths[4] %>
                                <td bgcolor="#7A1919" style="color:white">5</td>
                              <% else %>
                                <td></td>
                              <% end %>
                            <% end %>
                          </tr>
                        <% end %>
                        </tbody>
                      </table>
                      <!-- /.table-responsive -->
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% if current_user.admin %>
        <button data-toggle="modal" class="add-group-btn" data-target="#myModal">
          Add New Group
        </button>
      <% end %>
    </div>
  </section><!-- #contact -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
  <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
  <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>

</main>

<!--==========================
  Footer
============================-->
<footer id="footer">
  <div class="container">
    <div class="copyright">
      Engage Leadership Consulting&nbsp;&nbsp;&nbsp;info@engageleadershipconsulting.com
    </div>
    <div class="credits">
    </div>
  </div>
</footer><!-- #footer -->

<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <script>

    jQuery(document).ready(function($) {
        $("td[data-link]").click(function() {
            window.location = $(this).data("link");
        });

        $('[data-toggle="tooltip"]').tooltip();
    });

    $("[id$=myButtonControlID]").click(function(e) {
        //creating a temporary HTML link element (they support setting file names)
        var a = document.createElement('a');
        //getting data from our div that contains the HTML table
        var data_type = 'data:application/vnd.ms-excel';
        var table_div = document.getElementById('divTableDataHolder');
        var table_html = table_div.outerHTML.replace(/ /g, '%20');
        a.href = data_type + ', ' + table_html;
        //setting the file name
        a.download = 'contact_info.xls';
        //triggering the function
        a.click();
        //just in case, prevent default behaviour
        e.preventDefault();
    });

    $("[id$=myButtonControlID2]").click(function(e) {
        //creating a temporary HTML link element (they support setting file names)
        var a = document.createElement('a');
        //getting data from our div that contains the HTML table
        var data_type = 'data:application/vnd.ms-excel';
        var table_div = document.getElementById('strength_grid');
        var table_html = table_div.outerHTML.replace(/ /g, '%20');
        a.href = data_type + ', ' + table_html;
        //setting the file name
        a.download = 'teams.xls';
        //triggering the function
        a.click();
        //just in case, prevent default behaviour
        e.preventDefault();
    });
  </script>
</body>
</html>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Reveal Bootstrap Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Reveal
    Theme URL: https://bootstrapmade.com/reveal-bootstrap-corporate-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body id="body">

<!--==========================
  Top Bar
============================-->
<!--<section id="topbar" class="d-none d-lg-block">-->
  <!--<div class="container clearfix">-->
    <!--<div class="contact-info float-left">-->
      <!--<i class="fa fa-envelope-o"></i> <a href="mailto:contact@example.com">contact@example.com</a>-->
      <!--<i class="fa fa-phone"></i> +1 5589 55488 55-->
    <!--</div>-->
  <!--</div>-->
<!--</section>-->

<!--==========================
  Header
============================-->
<header id="header">
  <div class="container">

    <div id="logo" class="pull-left">
      <h1>
        <%= link_to root_path do %>
          Team<span>Sort</span>
        <% end %>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="#body"><img src="img/logo.png" alt="" title="" /></a>-->
    </div>

    <nav id="nav-menu-container">
      <ul class="nav-menu">
        <!-- /.dropdown -->
        <li class="menu-has-children"><a href=""><i class="fa fa-user fa-fw"></i></a>
          <ul>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-gear fa-fw"></i> Edit Account
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out fa-fw"></i> Logout
              <% end %>
            </li>
          </ul>
        </li>
        <!-- /.dropdown -->
      </ul>
    </nav><!-- #nav-menu-container -->
  </div>
</header><!-- #header -->

<main id="main">

  <section id="contact" class="wow fadeInUp">
    <div class="container">
      <div class="section-header">
        <h2><%= @group.title %></h2>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              Users
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email Address</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @group.users.each do |user| %>
                    <tr>
                      <% if user != current_user %>
                        <td><%= user.first_name %> <%= user.last_name %></td>
                        <td><%= user.email %></td>
                      <% end %>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
                <%= link_to 'Back', groups_path %>
              </div>
              <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
          </div>
          <!-- /.panel -->
        </div>
        <!-- /.col-lg-6 -->
      </div>
    </div>
  </section><!-- #contact -->

</main>

<!--==========================
  Footer
============================-->
<footer id="footer">
  <div class="container">
    <div class="copyright">
      Engage Leadership Consulting info@engageleadershipconsulting.com
    </div>
    <div class="credits">
    </div>
  </div>
</footer><!-- #footer -->

<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

</body>
</html>